#############################################################################
# Makefile for building: atom-heart-engine
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  atom-heart-engine.pro
# Template: app
# Command: /usr/lib/qt/bin/qmake -o Makefile atom-heart-engine.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -g -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/lib/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = atom-heart-engine1.0.0
DISTDIR = /home/marcecoll/Projects/Games/AtomHeartEngine/.tmp/atom-heart-engine1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Base/Game.cpp \
		Base/InputManager.cpp \
		Base/Object.cpp \
		Base/ObjectManager.cpp \
		Base/Scene.cpp \
		Base/SystemManager.cpp \
		Base/Systems/System.cpp \
		Base/Systems/BaseAudioSystem.cpp \
		Base/Systems/BaseDataSystem.cpp \
		Base/Systems/BaseInputSystem.cpp \
		Base/Systems/BaseRenderSystem.cpp \
		Base/Systems/BaseStateSystem.cpp 
OBJECTS       = Game.o \
		InputManager.o \
		Object.o \
		ObjectManager.o \
		Scene.o \
		SystemManager.o \
		System.o \
		BaseAudioSystem.o \
		BaseDataSystem.o \
		BaseInputSystem.o \
		BaseRenderSystem.o \
		BaseStateSystem.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		atom-heart-engine.pro Base/Game.hpp \
		Base/InputManager.hpp \
		Base/Object.hpp \
		Base/ObjectManager.hpp \
		Base/Scene.hpp \
		Base/SystemManager.hpp \
		Base/Systems/System.hpp \
		Base/Systems/BaseAudioSystem.hpp \
		Base/Systems/BaseDataSystem.hpp \
		Base/Systems/BaseInputSystem.hpp \
		Base/Systems/BaseRenderSystem.hpp \
		Base/Systems/BaseStateSystem.hpp Base/Game.cpp \
		Base/InputManager.cpp \
		Base/Object.cpp \
		Base/ObjectManager.cpp \
		Base/Scene.cpp \
		Base/SystemManager.cpp \
		Base/Systems/System.cpp \
		Base/Systems/BaseAudioSystem.cpp \
		Base/Systems/BaseDataSystem.cpp \
		Base/Systems/BaseInputSystem.cpp \
		Base/Systems/BaseRenderSystem.cpp \
		Base/Systems/BaseStateSystem.cpp
QMAKE_TARGET  = atom-heart-engine
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = atom-heart-engine


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: atom-heart-engine.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		atom-heart-engine.pro
	$(QMAKE) -o Makefile atom-heart-engine.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
atom-heart-engine.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile atom-heart-engine.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Game.o: Base/Game.cpp Base/Game.hpp \
		Base/InputManager.hpp \
		Base/SceneManager.hpp \
		Base/Scene.hpp \
		Base/ObjectManager.hpp \
		Base/Object.hpp \
		Base/Component.hpp \
		Base/TypeId.hpp \
		UI/UIManager.hpp \
		Base/Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o Base/Game.cpp

InputManager.o: Base/InputManager.cpp Base/InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputManager.o Base/InputManager.cpp

Object.o: Base/Object.cpp Base/Object.hpp \
		Base/Component.hpp \
		Base/TypeId.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Object.o Base/Object.cpp

ObjectManager.o: Base/ObjectManager.cpp Base/ObjectManager.hpp \
		Base/Object.hpp \
		Base/Component.hpp \
		Base/TypeId.hpp \
		Base/Game.hpp \
		Base/InputManager.hpp \
		Base/SceneManager.hpp \
		Base/Scene.hpp \
		UI/UIManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObjectManager.o Base/ObjectManager.cpp

Scene.o: Base/Scene.cpp Base/Scene.hpp \
		Base/ObjectManager.hpp \
		Base/Object.hpp \
		Base/Component.hpp \
		Base/TypeId.hpp \
		UI/UIManager.hpp \
		Base/Game.hpp \
		Base/InputManager.hpp \
		Base/SceneManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scene.o Base/Scene.cpp

SystemManager.o: Base/SystemManager.cpp Base/SystemManager.hpp \
		Base/TypeId.hpp \
		Base/Systems/BaseAudioSystem.hpp \
		Base/Systems/System.hpp \
		Base/Systems/BaseSceneSystem.hpp \
		Base/Systems/BaseRenderSystem.hpp \
		Base/Systems/BaseInputSystem.hpp \
		Base/Systems/BaseDataSystem.hpp \
		Base/Systems/BaseStateSystem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SystemManager.o Base/SystemManager.cpp

System.o: Base/Systems/System.cpp Base/Systems/System.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o System.o Base/Systems/System.cpp

BaseAudioSystem.o: Base/Systems/BaseAudioSystem.cpp Base/Systems/BaseAudioSystem.hpp \
		Base/Systems/System.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BaseAudioSystem.o Base/Systems/BaseAudioSystem.cpp

BaseDataSystem.o: Base/Systems/BaseDataSystem.cpp Base/Systems/BaseDataSystem.hpp \
		Base/Systems/System.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BaseDataSystem.o Base/Systems/BaseDataSystem.cpp

BaseInputSystem.o: Base/Systems/BaseInputSystem.cpp Base/Systems/BaseInputSystem.hpp \
		Base/Systems/System.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BaseInputSystem.o Base/Systems/BaseInputSystem.cpp

BaseRenderSystem.o: Base/Systems/BaseRenderSystem.cpp Base/Systems/BaseRenderSystem.hpp \
		Base/Systems/System.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BaseRenderSystem.o Base/Systems/BaseRenderSystem.cpp

BaseStateSystem.o: Base/Systems/BaseStateSystem.cpp Base/Systems/BaseStateSystem.hpp \
		Base/Systems/System.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BaseStateSystem.o Base/Systems/BaseStateSystem.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

